# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a:\Main\CODE\False_Position-college\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(757, 651)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.CardWidget_2 = CardWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_2.sizePolicy().hasHeightForWidth())
        self.CardWidget_2.setSizePolicy(sizePolicy)
        self.CardWidget_2.setMinimumSize(QtCore.QSize(0, 317))
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.CardWidget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TableWidget = TableWidget(self.CardWidget_2)
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.gridLayout_3.addWidget(self.TableWidget, 1, 0, 1, 1)
        self.SubtitleLabel = SubtitleLabel(self.CardWidget_2)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.gridLayout_3.addWidget(self.SubtitleLabel, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.CardWidget_2, 1, 0, 1, 1)
        self.CardWidget = CardWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget.sizePolicy().hasHeightForWidth())
        self.CardWidget.setSizePolicy(sizePolicy)
        self.CardWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.CardWidget.setObjectName("CardWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.CardWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tolarence_value = LineEdit(self.CardWidget)
        self.tolarence_value.setText("")
        self.tolarence_value.setObjectName("tolarence_value")
        self.gridLayout_2.addWidget(self.tolarence_value, 9, 0, 1, 2)
        self.calc_button = PrimaryPushButton(self.CardWidget)
        self.calc_button.setObjectName("calc_button")
        self.gridLayout_2.addWidget(self.calc_button, 10, 0, 1, 2)
        self.a_value = LineEdit(self.CardWidget)
        self.a_value.setText("")
        self.a_value.setObjectName("a_value")
        self.gridLayout_2.addWidget(self.a_value, 6, 0, 1, 1)
        self.b_value = LineEdit(self.CardWidget)
        self.b_value.setText("")
        self.b_value.setObjectName("b_value")
        self.gridLayout_2.addWidget(self.b_value, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
        self.CaptionLabel_4 = CaptionLabel(self.CardWidget)
        self.CaptionLabel_4.setObjectName("CaptionLabel_4")
        self.gridLayout_2.addWidget(self.CaptionLabel_4, 8, 0, 1, 1)
        self.TitleLabel = TitleLabel(self.CardWidget)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout_2.addWidget(self.TitleLabel, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.CaptionLabel_2 = CaptionLabel(self.CardWidget)
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.gridLayout_2.addWidget(self.CaptionLabel_2, 5, 0, 1, 1)
        self.CaptionLabel_3 = CaptionLabel(self.CardWidget)
        self.CaptionLabel_3.setObjectName("CaptionLabel_3")
        self.gridLayout_2.addWidget(self.CaptionLabel_3, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 2)
        self.equation_text = LineEdit(self.CardWidget)
        self.equation_text.setInputMask("")
        self.equation_text.setText("")
        self.equation_text.setObjectName("equation_text")
        self.gridLayout_2.addWidget(self.equation_text, 3, 0, 1, 2)
        self.CaptionLabel = CaptionLabel(self.CardWidget)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.gridLayout_2.addWidget(self.CaptionLabel, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.CardWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SubtitleLabel.setText(_translate("Form", "Table"))
        self.calc_button.setText(_translate("Form", "calculate"))
        self.CaptionLabel_4.setText(_translate("Form", "Enter your tolarence:"))
        self.TitleLabel.setText(_translate("Form", "FALSE POSITION"))
        self.CaptionLabel_2.setText(_translate("Form", "Enter the value for A (interval start):"))
        self.CaptionLabel_3.setText(_translate("Form", "Enter the value for B (interval end):"))
        self.CaptionLabel.setText(_translate("Form", "Enter your equation:"))
from qfluentwidgets import CaptionLabel, CardWidget, LineEdit, PrimaryPushButton, SubtitleLabel, TableWidget, TitleLabel
